/// <reference types="nativewind/types" />

<<<<<<< HEAD
// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.
=======
// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.
>>>>>>> 35ae86c4ddb1472145ca485587f2c87162186555
